x-gpu-deploy: &gpu_deploy
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  ffmpeg:
    image: jrottenberg/ffmpeg:5.1.2-nvidia2004
    entrypoint: []
    volumes:
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
    profiles: ["analysis", "ffmpeg"]
    <<: *gpu_deploy

  scene-detection:
    build: ./analysis/scene-detection
    image: ghcr.io/talebkanj/scene-detection
    volumes: &common_volumes
      - ${VISIONE_ROOT}:/data
      - ${VISIONE_CACHE}:/cache
      - ./common:/usr/src/visione:ro
    profiles: ["analysis", "scene-detection"]

  objects-colors:
    build: ./analysis/objects-colors
    image: ghcr.io/talebkanj/objects-colors
    volumes: *common_volumes
    profiles: ["analysis", "objects-colors"]

  objects-mrcnn-lvis:
    build: ./analysis/objects-mmdet
    image: ghcr.io/talebkanj/objects-mmdet
    environment: ["DETECTOR_NAME=mrcnn-lvis"]
    volumes: *common_volumes
    profiles: ["analysis", "objects-mrcnn-lvis"]
    <<: *gpu_deploy

  objects-vfnet64-coco:
    build: ./analysis/objects-mmdet
    image: ghcr.io/talebkanj/objects-mmdet
    environment: ["DETECTOR_NAME=vfnet64-coco"]
    volumes: *common_volumes
    profiles: ["analysis", "objects-vfnet64-coco"]
    <<: *gpu_deploy

  objects-frcnn-oiv4:
    build: ./analysis/objects-openimagesv4
    image: ghcr.io/talebkanj/objects-openimagesv4
    volumes: *common_volumes
    profiles: ["analysis", "objects-frcnn-oiv4"]

  features-clip-openai:
    build: ./analysis/features-clip
    image: ghcr.io/talebkanj/features-clip
    environment:
      - FEATURES_NAME=clip-openai
      - MODEL_HANDLE=openai/clip-vit-large-patch14
    volumes: *common_volumes
    profiles: ["analysis", "features-clip-openai"]
    <<: *gpu_deploy
    shm_size: 16g

  features-clip-laion:
    build: ./analysis/features-clip
    image: ghcr.io/talebkanj/features-clip
    environment:
      - FEATURES_NAME=clip-laion
      - MODEL_HANDLE=laion/CLIP-ViT-H-14-laion2B-s32B-b79K
    volumes: *common_volumes
    profiles: ["analysis", "features-clip-laion"]
    <<: *gpu_deploy
    shm_size: 16g

  features-clip-datacomp:
    build: ./analysis/features-clip
    image: ghcr.io/talebkanj/features-clip
    environment:
      - FEATURES_NAME=clip-datacomp
      - MODEL_HANDLE=laion/CLIP-ViT-L-14-DataComp.XL-s13B-b90K
    volumes: *common_volumes
    profiles: ["analysis", "features-clip-datacomp"]
    <<: *gpu_deploy
    shm_size: 16g

  features-biomed-clip:
    build: ./analysis/features-openclip
    image: ghcr.io/talebkanj/features-openclip
    environment:
      - FEATURES_NAME=biomed-clip
      - MODEL_HANDLE=hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224
    volumes: *common_volumes
    profiles: ["analysis", "features-biomed-clip"]
    <<: *gpu_deploy
    shm_size: 16g

  features-clip2video:
    build: ./analysis/features-clip2video
    image: ghcr.io/talebkanj/features-clip2video
    volumes: *common_volumes
    profiles: ["analysis", "features-clip2video"]
    <<: *gpu_deploy
    shm_size: 16g

  features-aladin:
    build:
      context: ./analysis/features-aladin
      secrets: ["asset_token"]
    image: ghcr.io/talebkanj/features-aladin
    volumes: *common_volumes
    profiles: ["analysis", "features-aladin"]
    <<: *gpu_deploy
    shm_size: 16g

  features-dinov2:
    build: ./analysis/features-dinov2
    image: ghcr.io/talebkanj/features-dinov2
    environment:
      - FEATURES_NAME=dinov2
      - MODEL=dinov2_vits14
    volumes: *common_volumes
    profiles: ["analysis", "features-dinov2"]
    <<: *gpu_deploy
    shm_size: 16g

  features-clipvip:
    build: ./analysis/features-clipvip
    image: ghcr.io/talebkanj/features-clipvip
    volumes: *common_volumes
    profiles: ["analysis", "features-clipvip"]
    <<: *gpu_deploy
    shm_size: 16g

  frame-cluster:
    build: ./analysis/frame-cluster
    image: ghcr.io/talebkanj/frame-cluster
    volumes: *common_volumes
    profiles: ["analysis", "frame-cluster"]

  str-object-encoder:
    build: ./index/str-object-encoder
    image: ghcr.io/talebkanj/str-object-encoder
    volumes: *common_volumes
    profiles: ["analysis", "str-object-encoder"]

  str-feature-encoder:
    build: ./index/str-feature-encoder
    image: ghcr.io/talebkanj/str-feature-encoder
    volumes: *common_volumes
    profiles: ["analysis", "str-feature-encoder"]

  faiss-index-manager:
    build: ./index/faiss-index-manager
    image: ghcr.io/talebkanj/faiss-index-manager
    volumes: *common_volumes
    profiles: ["analysis", "faiss-index-manager"]
